### PR TITLE
Fix pinned boxed async functions

### PR DESCRIPTION
**Pull request by raviqqe**
`#[async(pinned)]` and `#[async(pinned_send)` seem to be broken.

## My bad below

~~I could not run tests locally somehow.~~

```
> cargo test
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching package named `futures-await` found (required by `testcrate`)
location searched: file:///home/raviqqe/src/github.com/alexcrichton/futures-await
version required: = 0.1.0
```

### CODE REVIEW

**Comment by raviqqe** [comment]
`StableFuture` cannot be converted into trait objects as `poll` method's `self` is `PinMut`. What can I do?

https://github.com/withoutboats/futures-stable/blob/master/src/lib.rs#L33

**Comment by withoutboats** [comment]
So the situation is a bit complicated. You're right that `StableFuture` is not object safe, which is a problem. That's why `StableFuture` has methods `pin` and `pin_local`, which return `PinBox<Future + Send>` and `PinBox<Future>` respectively. Note - Future, not StableFuture. These methods use some unsafe code to make it all work, but its safe because the trait object is inside the pinbox.

The return type of pinned/pinned_send should actually be `PinBox<Future>` and `PinBox<Future + Send>`.

**Comment by raviqqe** [comment]
`PinBox<Future>: Future` doesn't appear to be met.

**Comment by withoutboats** [comment]
I'll work on your branch tomorrow and try to dig into the problem.

**Comment by withoutboats** [comment]
Yep, you're right. `PinBox<Future>` needs to implement `Future`, and this impl has to live in `futures-core`.

Let's just leave this open until we've resolved that issue.

**Comment by withoutboats** [comment]
@raviqqe Upstream futures-stable was just merged into the futures repository, which included the impls we need for this to work. The next step to solve the issue here is to set this to track the git branch of futures 0.2 with the nightly feature flag (instead of the crates.io 0.2-alpha version), and stop depending directly on futures-stable. That will make the impl exist.

Then this work can be rebased off that commit and we should be able to get it to work.

I'll probably make the PR to track the git branch next week if no one has made it before then. If you're interested, feel free to open another PR if you're interested in doing it. :)

**Comment by withoutboats** [comment]
Sorry to make you do this, but in the meantime we've merged these crates into rust-lang-nursery/futures-rs. Could you re-open this PR against that repository?

**Comment by withoutboats** [comment]
This PR has moved to rust-lang-nursery/futures-rs#916.

**Pull request closed without merging**
